# Generated by Django 5.0.9 on 2025-03-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark2',
        ),
    ]
