# Generated by Django 5.0.9 on 2025-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('primary_key', models.AutoField(db_column='pk', primary_key=True, serialize=False)),
                ('practice_char', models.CharField(blank=True, max_length=50, null=True)),
                ('practice_int', models.IntegerField(blank=True, null=True)),
                ('practice_dt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
