# Generated by Django 5.0.9 on 2025-03-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_practice_practice_char_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Practice',
            new_name='PracticeModels',
        ),
    ]
