# Generated by Django 5.0.9 on 2025-03-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_rename_practice_practicemodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicemodels',
            options={'verbose_name': 'practice_verbose_name', 'verbose_name_plural': 'practice_verbose_name_plural'},
        ),
        migrations.AlterModelTable(
            name='practicemodels',
            table='practice_db_table',
        ),
    ]
